### ISSUE TITLE
Seiryu, Phantom Beast

### ISSUE THREAD

**Issue by tritonicon** [TetrusAO/Wixoss-TCG-Cockatrice-Plugin#1]
Add text:  Life Burst: Banish 1 of your opponent's SIGNI with power 10000 or more.

Source: http://selector-wixoss.wikia.com/wiki/Seiryu,_Phantom_Beast , though Tetrus might have very well edited that page also, lol.

**Comment by TetrusAO** [comment]
Fixed, thanks
